### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Senbei123** [dannerph/homeassistant-eon-energiemonitor#2]
Sorry das ich so blöd frage, aber wie funktioniert dies?
Ich habe aktuell nur Zugriff auf meine intelligten SmartMeter Daten über die Webseite eon.com, bzw. dessen Kundenportal.
Wie kann ich die Daten nun abgreifen? Fehlt in der custom-component Einrichtung nicht die Authentifzierung?

**Comment by dannerph** [comment]
Diese Integration zeigt **keine Daten von einzelnen Smart Meter** an, **sondern den Stromverbrauch/erzeugung für eine ganze Region** (meist eine Gemeinde oder ein Landkreis). Die zu grundeliegenden Daten werden vom Netzbetreiber (in meinem Fall Bayernwerk) aufbereitet (Standardlastprofile, Lastgangmessungen, Einspeisemessungen und prognosen, ...) und in dem EON Energiemonitor Dashboard dargestellt. Ein Beispiel dieses Energiemonitors ist im Readme [verlinkt](https://energiemonitor.bayernwerk.de/demo).

Leider gibt es noch keinen Verzeichnisdienst, über welchen man sich den region_code holen kann, daher muss man wie in der Readme beschrieben sich den region_code selber aus dem Dashboard extrahieren.

**Comment by Senbei123** [comment]
Hi Philipp,

danke für die Erklärung, dann war es gestern Abend wohl doch zu spät 
geworden. ;)

Gruß,
Tristan

Am 2024-08-27 11:09, schrieb Philipp Danner:
